#!/bin/sh

if test ! -d template; then
  echo "Error: this script should be run from the parent of the template/ directory." 2>&1
  exit 1
fi

rm -f modelgen.mk
templates/gen > modelgen.mk
chmod -w modelgen.mk
