#!/bin/sh -x
case $check in
 *L) check="${check%L} -L";;
 *n) check="${check%n} -n";;
esac
set -x
$RANDLTL -F 50 -u -s 0 -f 10 -r 7 `cat $i.ap` |
while read f; do
  echo "Running with $f on $i with -$check $ltl2tgba"
  (case $i in
    *.rg)
      if [ ! -f $i.snow ]; then
        $TIME $LTLGSPNSRG  -$check $ltl2tgba $i "$f"          `cat $i.ap` 2>&1
      else
	PROPS=`echo $f | sed 's/P[0-9]/&,\n/g' | sed 's/.*P/P/' |
               grep P | sort -u | tr -d '\n' | sed 's/,$//'`
	$SNOW -m $i.cami -p $i.snow -f "$PROPS"
	$TRANS2PL model
	mv model.nettmp model.net
        $TIME $LTLGSPNSRG  -$check $ltl2tgba model "$f" \
              `echo $PROPS | tr ',' ' '` 2>&1
      fi;;
    *)
      $TIME $LTLGSPNSSP -$check $ltl2tgba $i "$f" "$i.con" `cat $i.ap` 2>&1 ;;
  esac
    test -f *.mark || touch "x.mark"
    test -f *.event || touch "x.event"
    du -b *.mark *.event | cut -f 1
  ) |
  tee tmp
  sed -n '/^$/n;
          /^Command exited with non-zero status/n;
          2,$s/[^0-9.]//g;
          s/^[.]//;
          1x;
          2,$H;
          $x;
          $s/\n/,/g;
          $p' < tmp >> $res
done
